config/routes.rb
Rails.application.routes.draw do

  post 'firetalk_debaters/destroy', to: 'firetalk_debaters#destroy'

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller

  root 'home#index'

  get '/feedbacks/new', to: 'feedbacks#new'
  post '/feedbacks/new', to: 'feedbacks#create'

  get 'home/news'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/join', to: 'debates#join'

  post '/login', to: 'sessions#create'
  post '/subscribe', to: 'home#save_subscription'

  get '/change_password', to: 'users#change_password'
  post '/update_password', to: 'users#update_password'

  get '/forgot_password', to: 'users#forgot_password'
  post '/forgot_password', to: 'users#reset_password'

  get '/users', to: 'users#index'

  get '/invites', to: 'application#grab_invites'
  put '/invites', to: 'invites#update'

  get '/join_random_firetalk', to: 'random_firetalks#join'
  get '/watch_random_firetalk', to: 'random_firetalks#watch'

  get '/join_firetalk', to: 'firetalks#join'

  get '/firetalk_message', to: 'firetalk_messages#new'
  post '/firetalk_message', to: 'firetalk_messages#create'

  resources :users do
    get :validate_email
    resources :debates
    resources :firetalks
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :validate_code
	before_create :save_fullname
	has_many :debates
	has_many :firetalks
	has_many :debate_users
	has_many :firetalk_users
	has_many :posts

	has_many :invites
	has_many :moderator_invites
	has_many :notifications

	has_secure_password
	validates :password, presence: true, confirmation: true, length: { minimum: 7 }
	validates_uniqueness_of :email, :case_sensitive => false

	private
	def validate_code
		if self.validation_code.nil? || self.validation_code.blank
			self.validation_code = SecureRandom.urlsafe_base64.to_s
		end
	end

	def save_fullname
		self.fullname = self.firstname + " " + self.lastname
	end
end

app/controllers/users_controller.rb
require 'bcrypt'
require 'securerandom'

class UsersController < ApplicationController
  include BCrypt

  def index
    if (session[:user_id])
      @users = User.where.not(:id => session[:user_id])
      respond_to do |format|
        format.json {render :json => @users.where("lower(fullname) like ?", "%#{params[:q].downcase}%")}
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.email_validation(@user).deliver
      flash[:success] = true
      flash[:message] = "Account successfully created! Check your E-mail for a verification link"
      redirect_to root_url
    else
      flash[:success] = true
      flash[:message] = "You have not completed the required fields!"
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    @total = []
    @debates = @user.debates
    @firetalks = @user.firetalks
    @firetalk_debaters = FiretalkDebater.where(:user_id => @user.id)

    @posts = @user.posts
    @debates.each do |debate|
      @total.push(debate)
    end
    @firetalks.each do |firetalk|
      @total.push(firetalk)
    end
    @firetalk_debaters.each do |firetalk_debater|
      @total.push(firetalk_debater)
    end
    @posts.each do |post|
      @total.push(post)
    end
    @total.sort_by! { |model| model.created_at.to_date}
  end

  def edit
  end

  def update
  end

  def validate_email
    user = User.find_by_validation_code(params[:user_id])
    if user
      # CHANGE TO OMMIT PASSWORD
      #params[:user].delete(:password) if params[:password].blank?
      sql = "UPDATE users SET is_validated = 't' WHERE id = #{user.id}"
      ActiveRecord::Base.connection.execute(sql)
      flash[:success] = true
      flash[:message] = "E-mail successfully verified!"
      redirect_to login_path
    else
      flash[:success] = false
      flash[:message] = "Sorry, that user does not exist!"
      redirect_to login_path
    end
  end

  def forgot_password
  end

  def reset_password
    @user = User.find_by_email(params[:email])
    # make new password, and send new password to email
    temp_password = SecureRandom.hex(10)
    @user.password = temp_password
    if !@user
      flash[:success] = true
      flash[:message] = "Could not find user under that e-mail"
      redirect_to '/forgot_password'
    elsif @user.save!
      UserMailer.email_password(@user, temp_password).deliver
      flash[:success] = true
      flash[:message] = "Check your email for your new temporary password!"

      redirect_to '/login'
    else
      flash[:success] = true
      flash[:message] = "Error update your password, database error"
      redirect_to '/forgot_password'
    end
  end

  def change_password
    @user = User.find(session[:user_id])
  end

  def update_password
    @user = User.find(session[:user_id])
    if @user.authenticate(params[:user][:current_password]) && @user.update(password_params)
      flash[:success] = true
      flash[:message] = "Successfully updated password!"
      redirect_to '/'
    else
      flash[:success] = false
      flash[:message] = "Failed to update password, make sure they match"
      redirect_to '/change_password'
    end

  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/change_password.html.erb
<%= form_for(@user, :url => update_password_path(:protocol => 'https'), :method => 'POST') do |f| %>
  <%= f.password_field(:current_password, {:placeholder => 'Current Password'}) %>
  <%= f.password_field(:password, {:placeholder => 'New Password'}) %>
  <%= f.password_field(:password_confirmation, {:placeholder => 'Repeat New Password'}) %>
  <%= f.submit("Update Password") %>
<% end %>

app/views/users/forgot_password.html.erb
<h1>Forgot your password? Enter your email here</h1>
<%= form_tag('/forgot_password') do %>
  <%= email_field_tag('email', nil, class: 'special_input') %>
  <%= submit_tag('Send reset') %>
<% end %>

app/views/users/new.html.erb
<div class="section">
	<div class="col span_10_of_10">
		<div class="center-col-shadow">
			<div class="">
				<div class="signin-box-container">
					<div class="signin-box">
						<div class="section centerhor">
							<h1>Join our community!</h1>
						</div>
						<div class="section centerhor">
							<em>Already have an account?
								<%= link_to 'Login here.', login_path, {:method => 'GET'} %>
							</em>
						</div>
							</br></br>
						<div class="section centerhor">
							<%= form_for(@user, :url => users_path(:protocol => 'https')) do |f| %>
							First Name
							</br>
							<%= f.text_field(:firstname, {:placeholder => "First Name", :required => true, :class => "forms"}) %>
							</br>
							</br>
							Last Name
							</br>
							<%= f.text_field(:lastname, {:placeholder => "Last Name", :required => true, :class => "forms"}) %>
							</br>
							</br>
							Email
							</br>
							<%= f.text_field(:email, {:placeholder => "E-mail", :required => true, :class => "forms"}) %>
							</br>
							</br>
							Create a Password
							</br>
							Must be 7 or more characters
							</br>
							<div>
								<%= f.password_field(:password, {:placeholder => "Password", :required => true, :class => "forms"}) %>
							</div>
							</br>
							Confirm Password
							</br>
							<div>
							<%= f.password_field(:password_confirmation, {:placeholder => "Confirm Password", :required => true, :class => "forms"}) %>
							</div>
							</br>
						</div>
						<div class="section centerhor">
							<%= f.submit("Create Account", :class => "button") %>

							<% end %>
							</br>
						</div>
						<div class="section centerhor notif">
   							<em>
 								<% if !flash[:message].nil? %>
   								<%= flash[:message] %>
   								<% end %>
 							</em>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="section">
	<div class="col span_10_of_10">
    <div class="center-col-shadow">
      <div class="prof-container">
        <div class="prof">

<div class="user-info-box-container">
  <div class="user-info-box">
    <!-- Here is where the user information will be printed -->
      <div class="user-info-content">
      <div class="user-info-name">
        <h3>
          <%= @user.firstname %>
          <%= @user.lastname %>
        </h3>
      </div>

      <div class="user-info-school">
        <%= @user.school %>
      </div>

  <!-- just a thought, maybe keep track of how much they have participated? -->

      <div class="user-info-total-debates">
        <% total_debate_instances = @debates.length + @firetalks.length + @firetalk_debaters.length %>
        <%= "Total debates: " + total_debate_instances.to_s %>
      </div>


      <div class="user-info-reset-password">
        <%= session[:user_id].to_s + "" + @user.id.to_s %>
        <% if session[:user_id] == @user.id %>
        <%= nav_link("Reset Password", change_password_path, :method => "get") %>
        <% end %>
      </div>
    </div>

</div>
</div>






<!--
Here is all the profile activity ordered by date created
The render method you see is rendering a partial. For every iteration of the loop,
it will render the corresponding partials:
  Firetalk: /firetalks/_firetalk.html.erb
  FiretalkDebater: /firetalk_debaters/_firetalk_debater.html.erb
  and so on for debates and posts
-->


<div class="user-activity-container">

  <div class="bordered-box-container">
    <div class="bordered-box">


<div class="user-activity-box-container">
  <div class="centerhor">
    <h3>
  Recent activity
</h3>
</div>
  <div class="user-activity-box">
    <% @total.each do |obj| %>
      <% if obj %>
  <div class="user-activity-item-container">
  <div class="user-activity-item">


    <%= render(:partial => obj, :locals => {:obj => obj}) %>
    <% end %>
  <% end %>


  </div>
</div>
</br>

</div>
</div>

</div>
</div>

</div>


</div>
</div>
</div>
</div>
</div>