config/routes.rb
Rails.application.routes.draw do

  post 'firetalk_debaters/destroy', to: 'firetalk_debaters#destroy'

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller

  root 'home#index'

  get '/feedbacks/new', to: 'feedbacks#new'
  post '/feedbacks/new', to: 'feedbacks#create'

  get 'home/news'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/join', to: 'debates#join'

  post '/login', to: 'sessions#create'
  post '/subscribe', to: 'home#save_subscription'

  get '/change_password', to: 'users#change_password'
  post '/update_password', to: 'users#update_password'

  get '/forgot_password', to: 'users#forgot_password'
  post '/forgot_password', to: 'users#reset_password'

  get '/users', to: 'users#index'

  get '/invites', to: 'application#grab_invites'
  put '/invites', to: 'invites#update'

  get '/join_random_firetalk', to: 'random_firetalks#join'
  get '/watch_random_firetalk', to: 'random_firetalks#watch'

  get '/join_firetalk', to: 'firetalks#join'

  get '/firetalk_message', to: 'firetalk_messages#new'
  post '/firetalk_message', to: 'firetalk_messages#create'

  resources :users do
    get :validate_email
    resources :debates
    resources :firetalks
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :debates
end

app/models/debate.rb
class Debate < ActiveRecord::Base
	require 'opentok'
	OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

	before_create :save_tok_session_id

	belongs_to :user
	belongs_to :category
	belongs_to :debate_style
	has_many :debate_users
	has_many :debater_invites
	has_many :moderator_invites

	accepts_nested_attributes_for :debater_invites
	accepts_nested_attributes_for :moderator_invites

	private
	def save_tok_session_id
		opentok = OpenTok::OpenTok.new '45241592', 'b099560439c52ed195d79cb7c15fbae1d9b33f1e'
		session = opentok.create_session
		self.tok_session_id = session.session_id
	end
end

app/models/debate_invites.rb
class DebateInvites < ActiveRecord::Base
  belongs_to :debate
end

app/models/debate_styles.rb
class DebateStyles < ActiveRecord::Base
  has_many :debates
end

app/models/debate_user.rb
class DebateUser < ActiveRecord::Base
	belongs_to :debate
	belongs_to :user
end

app/models/debater_invite.rb
class DebaterInvite < ActiveRecord::Base

  after_create :send_invite

  belongs_to :debate
  belongs_to :user
  
  private
  def send_invite
  end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/firetalk.rb
class Firetalk < ActiveRecord::Base
  require 'opentok'
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  before_create :save_tok_session_id

  #attr_accessible :user_ids
  belongs_to :user
  has_many :firetalk_debaters
  has_many :firetalk_messages
  has_many :users, :through => :firetalk_debaters

  accepts_nested_attributes_for :firetalk_debaters
  attr_reader :user_tokens
  #validates :user, presence: true

  def user_tokens=(ids)
    # TODO: validate users with ids, not working for now
    #self.user_ids = ids.split(",")
  end

  def random_firetalk(params)
    self.user_id = params[:user_id]
    self.topic = params[:topic]
    self.tok_session_id = params[:tok_session_id]
    self.name = "Random Firetalk!"
  end

  private
  def save_tok_session_id
    opentok = OpenTok::OpenTok.new '45241592', 'b099560439c52ed195d79cb7c15fbae1d9b33f1e'
    session = opentok.create_session
    self.tok_session_id = session.session_id
  end
end

app/models/firetalk_debater.rb
class FiretalkDebater < ActiveRecord::Base
  belongs_to :firetalk
  belongs_to :user
end

app/models/firetalk_message.rb
class FiretalkMessage < ActiveRecord::Base
  belongs_to :firetalk
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user 
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :validate_code
	before_create :save_fullname
	has_many :debates
	has_many :firetalks
	has_many :debate_users
	has_many :firetalk_users
	has_many :posts

	has_many :invites
	has_many :moderator_invites
	has_many :notifications

	has_secure_password
	validates :password, presence: true, confirmation: true, length: { minimum: 7 }
	validates_uniqueness_of :email, :case_sensitive => false

	private
	def validate_code
		if self.validation_code.nil? || self.validation_code.blank
			self.validation_code = SecureRandom.urlsafe_base64.to_s
		end
	end

	def save_fullname
		self.fullname = self.firstname + " " + self.lastname
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'searchbing'
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  def index
    if session[:user_id]
      redirect_to home_news_path
    end
    @newslettersubscription = NewsletterSubscription.new
  end

  def save_subscription
    @newslettersubscription = NewsletterSubscription.new(new_params)
    if @newslettersubscription.save
      flash[:message] = true
      flash[:message] = "Successfully Subscribed!"
      redirect_to root_path
    end
  end

  def news
    if session[:user_id]
      @user = User.find(session[:user_id])
      @bing_news = Bing.new('wQ4qB9R18dzlg2WTWasb2xoA/RRb9LzN5VfcbF197YI', 15, 'News')
      @news_items = @bing_news.search("")
      @firetalks_in_progress = Firetalk.where(:finished => false)
    else
      flash[:message] = true
      flash[:message] = "You must be logged in to use this feature!"
      redirect_to login_path
    end
  end

  private
  def new_params
    params.require(:newsletter_subscription).permit(:email)
  end
end

app/helpers/debates_helper.rb
module DebatesHelper
  def link_to_add_moderator_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_moderator_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="section">
	<div class="col span_10_of_10 toppad">
    	<div class="center-col-shadow">




    		<!--MAIN SECTION START-->

			<div class="section home-container">


				<div class="section home-section centerhor">
			<% if !flash[:message].nil? %>
		    <%= flash[:message] %>
		    <% end %>
			</div>



						


					<div class="bordered-box-container welcome-news">
						<div class="">


							<div  class="centerhor">
						<h1>
						
								Welcome to Debatable <span>beta</span>!
							
						</h1>
					</div>
					</br>
						
					</div>
					</div>

					<div class="bordered-box-container faqs-news">
						<div class="bordered-box">
							<div class="centerhor" style="text-decoration:underline;">
							FAQ
						</div>
					</br>
					<div>
						<strong>
							What's goin' on here?
						</strong>
						</div>
						</br>
						<div>
						
							<em>
								- Debatable is a live-video debating platform. We're here to help you
								speak your mind and reach the community.
							</em>
						
					</div>
				</br>
						<div>
							<strong>
							What's a firetalk?
						</strong>
						</div>
					</br>
						<div>
							<em>
								- A firetalk is an elimination-round debate game.
								One can create a firetalk and invite their friends or
								they could join a random firetalk with random users
								and discuss the topic of the day!
							</em>
						</div>
						</br>

						<div>
							<strong>
							How does a firetalk work?
						</strong>
						</div>
					</br>
						<div>
							<em>
								- In each round, everyone gets to talk
								once for 45 seconds, and you can talk about the topic in order to gain votes. The player at the end of each round that has the least amount of votes is eliminated. This continues until a winner is chosen!
							</em>
						</div>
						</br>

						<div>
							<strong>
							How should one use Debatable?
						</strong>
						</div>
					</br>
						<div>
							<em>
								- While this website works on nearly any device, we do not support iOS.
								To experience Debatable to its fullest extend, use our site on a laptop
								or desktop. Not only will you have a larger screen than a mobile device,
								but you will more than likely also experience better quality video and audio.
							</em>
						</div>
					</div>
					</div>






					<div class="bordered-box-container options-news">
						<div class="bordered-box centerhor">

							<div>
								<em>
							Todays topic:
						</em>

					</br>

							<h3>
							<%= @topic %>
						</h3>


						</div>


						<hr>


						<div>

							<em>
								Discuss todays topic in a random firetalk!
							</em>
							</br>
							</br>
							<div>
							<%= link_to 'Go Debate!', join_random_firetalk_path, {:class => "home-butts button", :method => 'GET'} %>
						</div>

						</div>
					</br>

							<em>
								Watch a random firetalk!  

							</em>
							</br>
							</br>
						<div>
							<%= link_to 'Watch Debate!', watch_random_firetalk_path, {:class => "home-butts button", :method => 'GET'}%>
						</div>
					
							<div>
		<% if @firetalks_in_progress %>
		<% @firetalks_in_progress.each do |firetalk| %>
			<%= "Debaters" %>
			<% firetalk.firetalk_debaters.each do |debater| %>
			<% end %>
		<% end %>
		<% end %>
	</div>
	<hr>
						
												
						<em>
								Not a part of the community yet? Create an account and start debating today. 

							</em>
							</br>
							</br>
						<div>
							<%= link_to "Signup", new_user_path, {:class => "home-butts button", :method => 'GET'} %>
						</div>

</br>

						<em>
								Already have an account? 

							</em>
							</br>
							</br>
							<div>
							<%= link_to 'Login', login_path, {:class => "home-butts button", :method => 'GET'} %>
						</div>
						


						</div>
					</div>





							
						
					

			</div>

			<!--MAIN SECTION END-->



		</div>
	</div>
</div>

app/views/home/index2.html.erb
<div class="container">
<div class="row">
<div class="col-md-2">
	menu

	</div>
		<div class="col-md-8">
<a name="mission"></a>
<div class="jumbotron">
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
	<h2><%= image_tag("chitchat_nav_white.png", :class => "text-center")%>
		<strong>Welcome to Debatable!</strong>
	</h2>
</div>
</div>
<div class="row">
	<div class="col-md-12">
	<h3>
		<span class="glyphicon glyphicon-forward" aria-hidden="true"></span><em>
		Our Mission:</em></h3>
	<div class="text-justify">
	<blockquote>
		<p>
			Here at debatable, we want to give people the stage to share their opinions and be understood by their communities. Debatable is a live-video debating social media platform that bridges face to face conversation and social media interaction. Come join us on <strong>February 20th</strong> for our launch! <br><em>- The Debatable Team</em>
		</p>
	</blockquote>
</div>
</div>
</div>
				<!--<div class="row">
					<div class="col-md-12 text-center">
						<h2>Beta Coming Soon!</h2>
					</div>
				</div>-->
</div>
		</div>


-->
<!--
<a name="connect"></a>
<div class="jumbotron">
	<div class="container">

		<div class="row">
			<div class="container text-center">
				<h3><strong>Stay connected and be the first to use Debatable!</strong></h3>
			</div>
		</div>
	</br>
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<h4 class="text-center">
				Sign up for our newsletter:</h4>
			</div>
			<div class="col-md-3"></div>
		</div>

		<%= form_for @newslettersubscription, :url => subscribe_path do |f| %>
		<div class="row">
			<div class="col-md-3">
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<%= f.text_field :email, :placeholder => "Email", :class => "form-control" %>
				</div>
			</div>
			<div class="col-md-3">
			</div>
		</div>
		<div class="row">
			<div class="col-md-5">
			</div>
			<div class="col-md-2 text-center">
				<%= f.submit 'Submit', :class => "btn btn-default" %>
			</div>
			<div class="col-md-5">
			</div>
		</div>
		<% end %>
	</br>
	<!--
	<div class="row">
		<div class="col-md-5"></div>
		<div class="col-md-2">
			<h3 class="text-center"><strong>Follow us!
			</strong></h3>
		</div>

		<div class="col-md-5"></div>

	</div>
	<div class="row">
		<div class="col-md-5"></div>
		<div class="col-md-1">
			<%= link_to image_tag("facebook_small.png", :class => "img-responsive") %>
		</div>
		<div class="col-md-1">
			<%= link_to image_tag("twitter_small.png", :class => "img-responsive") %>
		</div>
		<div class="col-md-5"></div>
	</div>

</div>
</div>
-->





<a name="features"></a>
<div class="jumbotron">
	<div class="container">
		<div class="container">
<div class="row">
	<div class="col-md-12 text-center">
	<!--<h2>What to expect:</h2>-->
	<h2>We're here to help you speak your mind.</h2>
	</div>	
</div>

		</br>
<div class="row">
	<!--<div class="col-md-2">
	</div>-->
	<div class="col-md-12">
	<h3><span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
	Debates
	</h3>
	<blockquote>
	Debate and discuss any topic face-to-face with whoever you want whether they live across the globe or across the nation.
	</blockquote>
	</div>
	<!--<div class="col-md-2"></div>-->
	</div>

	<div class="row">
	<!--<div class="col-md-2"></div>-->
	<div class="col-md-12">
	<h3><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
	Firetalk 
	</h3>
	<blockquote>
	Battle your friends with your words as you fight through rounds of elimination in a fast-paced debatable game.
	</blockquote>
	</div>
	<!--<div class="col-md-2"></div>-->
	</div>


<div class="row">
<!--<div class="col-md-2"></div>-->
<div class="col-md-12">
	<h3><span class="glyphicon glyphicon-flag" aria-hidden="true"></span>
	Moderation
	</h3>
	<blockquote>
	With the option of adding a moderator, you will be able to ensure there is a neutral participant, as well as keep the discussion on-topic.
	</blockquote>
	</div>
	<!--<div class="col-md-2"></div>-->
</div>


<div class="row">
	<!--<div class="col-md-2"></div>-->
	<div class="col-md-12">
	<h3><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
	Social Media
	</h3>
	<blockquote>
	Engage in a true social atmosphere centered on intelligent debate and discussion. Where every status update can turn into the next big debate or firetalk; debatable truly brings the town hall to the web.
	</blockquote>
	</div>
	<!--<div class="col-md-2"></div>-->
</div>


<div class="row">
	<!--<div class="col-md-2"></div>-->
	<div class="col-md-12">
	<h3><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span>
	Share Debates
	</h3>
	<blockquote>
	Share debates on Facebook, Twitter, and other existing social media to show the world what you have been up to.
	</blockquote>
	</div>-->
	<!--<div class="col-md-2"></div>-->





</div>
</div>
</div>
</div>

<a name="about"></a>
<div class="jumbotron">
		<div class="container">
			<div class="row">
			<div class="col-md-1">
</div>
			<div class="col-md-10">
	<h2 class="text-center">The Team:</h2>
</div>
			<div class="col-md-1">
</div>
</div>
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
		<%= image_tag("debatableteampic.png", :class => "img-thumbnail img-responsive") %>
	</div>
	<div class="col-md-2"></div>
</div>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10"><hr></div>
	<div class="col-md-1"></div>
</div>
	<div class="row">
	<div class="col-md-2"></div>
	<div class="center-block hidden-sm hidden-xs col-md-2">
    				<div class="text-center">
	<span style="font-size:4em;" class="glyphicon glyphicon-tint" aria-hidden="true"></span>
</div>
</div>
	<div class="text-center col-md-6">
        <h4>William <br>Felix</h4>
        <h5>Front-end Developer and Co-Founder</h5>
</div>
<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="center-block hidden-sm hidden-xs col-md-2">
    				<div class="text-center">
	<span style="font-size:4em;" class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
</div>
</div>
	<div class="text-center col-md-6">
        <h4>Garrick<br> Król</h4>
        <h5>Senior Developer and Co-Founder</h5>
</div>
<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="center-block hidden-sm hidden-xs col-md-2">
    				<div class="text-center">
	<span style="font-size:4em;" class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
</div>
</div>
	<div class="text-center col-md-6">
        <h4>Brandon<br> Prinz</h4>
        <h5>CEO and Co-Founder<br>
</div>
<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="center-block hidden-sm hidden-xs col-md-2">
    				<div class="text-center">
	<span style="font-size:4em;" class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span>
</div>
</div>
	<div class="text-center col-md-6">
        <h4>Dane<br> Halvorson</h4>
        <h5>COO and Co-Founder<br>
</div>
<div class="col-md-2"></div>
</div>




<!--
<div class="row">
	<div class="col-md-2"></div>
	<div class="center-block hidden-sm hidden-xs col-md-2">
    				<div class="text-center">
	<span style="font-size:4em;" class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
</div>
</div>
	<div class="text-center col-md-6">
        <h4>Marielle<br> Trumbauer</h4>
        <h5>Head of Finance and Co-Founder</h5>
</div>
<div class="col-md-2"></div>
</div>



<div class="row">
<div class="col-sm-6 col-md-2">
<div class="thumbnail">
<div class="center-block img-thumbnail hidden-sm hidden-xs">
    				<div class="text-center">
	<span style="font-size:4em;" class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
</div>
</div>
	<div class="caption text-center">
        <h4>Garrick<br> Król</h4>
        <h5>Senior Developer and Co-Founder</h5>
</div>
</div>
</div>
</div>

<div class="row">
		<div class="col-sm-6 col-md-2">
    		<div class="thumbnail">
	<div class="center-block img-thumbnail hidden-sm hidden-xs">
    				<div class="text-center">
	<span style="font-size:4em;" class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
</div>
</div>
	<div class="caption text-center">
        <h4>Brandon<br> Prinz</h4>
        <h5>CEO and Founder<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </h5>
</div>
</div>
</div>
</div>


<div class="row">
<div class="col-sm-6 col-md-2">
    		<div class="thumbnail">
    			<div class="center-block img-thumbnail hidden-sm hidden-xs">
    				<div class="text-center">
	<span style="font-size:4em;" class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span>
</div>
</div>
	<div class="caption text-center">
        <h4>Dane<br> Halvorson</h4>
        <h5>COO and Co-Founder<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h5>
</div>
</div>
</div>
</div>

<div class="row">
<div class="col-sm-6 col-md-2">
    		<div class="thumbnail">
	<div class="center-block img-thumbnail hidden-sm hidden-xs">
    				<div class="text-center">
	<span style="font-size:4em;" class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
</div>
</div>
	<div class="caption text-center">
        <h4>Marielle<br> Trumbauer</h4>
        <h5>Head of Finance and Co-Founder</h5>
</div>
</div>
</div>
</div>

-->
<div class="row">
		<div class="container text-center">
			<h3>
				Questions?</br>
			Contact us at about@debatable.co
		</h3>
	</div>
</div>
</div>
</div>
</div>



<div class="col-md-2">

	<div class="text-center">
<div>
<%= button_to "Login", login_path, {:class => "btn btn-default", :method => "get"} %>
</div>
</br>
<div>
<%= button_to "Signup", new_user_path, {:class => "btn btn-default", :method => "get"} %>
</div>
</div>

	</div>



</div>
</div>
</div>
</div>
</div>

















<!--
<div>
<div>
<%= button_to "Login", login_path, {:class => "btn btn-default", :method => "get"} %>
</div>
</br>
<div>
<%= button_to "Signup", new_user_path, {:class => "btn btn-default", :method => "get"} %>
</div>
</div>
-->














<!-- END OF BOOTSTRAPSTYLES-->

app/views/home/news.html.erb
<div class="section">
	<div class="col span_10_of_10 toppad">
    	<div class="center-col-shadow">




    		<!--MAIN SECTION START-->

			<div class="section home-container">


				<div class="section home-section centerhor">
			<% if !flash[:message].nil? %>
		    <%= flash[:message] %>
		    <% end %>
			</div>



						

					<div class="bordered-box-container welcome-news">
						<div class="">

							<div  class="centerhor">
						<h1>
							<strong>
								Welcome to Debatable <span>beta</span>!
							</strong>

						</h1>
					</div>
					</br>
						
					</div>
					</div>

					<div class="bordered-box-container faqs-news">
						<div class="bordered-box">
													<div class="centerhor" style="text-decoration:underline;">
							FAQ
						</div>
					</br>
					<div>
						<strong>
							What's goin' on here?
						</strong>
						</div>
						</br>
						<div>
						
							<em>
								- Debatable is a live-video debating platform. We're here to help you
								speak your mind and reach the community.
							</em>
						
					</div>
				</br>
						<div>
							<strong>
							What's a firetalk?
						</strong>
						</div>
					</br>
						<div>
							<em>
								- A firetalk is an elimination-round debate game.
								One can create a firetalk and invite their friends or
								they could join a random firetalk with random users
								and discuss the topic of the day!
							</em>
						</div>
						</br>

						<div>
							<strong>
							How does a firetalk work?
						</strong>
						</div>
					</br>
						<div>
							<em>
								- In each round, everyone gets to talk
								once for 45 seconds, and you can talk about the topic in order to gain votes. The player at the end of each round that has the least amount of votes is eliminated. This continues until a winner is chosen!
							</em>
						</div>
						</br>

						<div>
							<strong>
							How should one use Debatable?
						</strong>
						</div>
					</br>
						<div>
							<em>
								- While this website works on nearly any device, we do not support iOS.
								To experience Debatable to its fullest extend, use our site on a laptop
								or desktop. Not only will you have a larger screen than a mobile device,
								but you will more than likely also experience better quality video and audio.
							</em>
						</div>

					</div>
					</div>


				<div class="bordered-box-container options-news">
					<div class="bordered-box centerhor">
						<div>
							<em>
							Todays topic:
							</em>
							</br>
							<h3>
							<%= @topic %>
							</h3>
						</div>

							<hr>

						<div>

							<em>
								Discuss todays topic in a random firetalk!
							</em>
							</br>
							</br>
							<div>
							<%= link_to 'Go Debate!', join_random_firetalk_path, {:class => "home-butts button", :method => 'GET'} %>
						</div>

						</div>
					</br>

							<em>
								Watch a random firetalk!  

							</em>
							</br>
							</br>
						<div>
							<%= link_to 'Watch Debate!', watch_random_firetalk_path, {:class => "home-butts button", :method => 'GET'}%>
						</div>

						</br>
							<div class="active-ft-container">
							<div class="active-ft-label">
								Join an active firetalk!
							</div>

								<div class="active-firetalks">
								<% if @firetalks_in_progress %>
									<% @firetalks_in_progress.each do |firetalk| %>
									<div class="active-ft-item-container">
										<div class="active-ft-link-container">
									<div class="active-ft-link">
									<%= link_to 'Watch Firetalk!', user_firetalk_path(:id => firetalk.id, :user_id => firetalk.user_id), {:class => "ft-link", :method => 'GET'} %>
								</div>
									<% if !firetalk.full %>
									<div class="active-ft-link">
										<%= link_to 'Join Firetalk!', join_firetalk_path(:id => firetalk.id), {:class => "ft-link", :method => 'GET'} %><% end %>
									</div>
								</div>
									
									<div class="active-ft-debaters-container">
									<div class="active-ft-debaters-label">
										debaters:
									</div>
									<div class="active-ft-debaters-item">
										<% firetalk.firetalk_debaters.each do |debater| %><% end %>
									</div>
								</div>
								</div>
										
									<% end %>
								<% end %>
							</div>
						</div>


						</div>
					</div>

							
						
					

			</div>

			<!--MAIN SECTION END-->



		</div>
	</div>
</div>

app/views/home/show.html.erb
<h1>NEW ACCOUNT SUCCESSFUL</h1>