config/routes.rb
Rails.application.routes.draw do

  post 'firetalk_debaters/destroy', to: 'firetalk_debaters#destroy'

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller

  root 'home#index'

  get '/feedbacks/new', to: 'feedbacks#new'
  post '/feedbacks/new', to: 'feedbacks#create'

  get 'home/news'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/join', to: 'debates#join'

  post '/login', to: 'sessions#create'
  post '/subscribe', to: 'home#save_subscription'

  get '/change_password', to: 'users#change_password'
  post '/update_password', to: 'users#update_password'

  get '/forgot_password', to: 'users#forgot_password'
  post '/forgot_password', to: 'users#reset_password'

  get '/users', to: 'users#index'

  get '/invites', to: 'application#grab_invites'
  put '/invites', to: 'invites#update'

  get '/join_random_firetalk', to: 'random_firetalks#join'
  get '/watch_random_firetalk', to: 'random_firetalks#watch'

  get '/join_firetalk', to: 'firetalks#join'

  get '/firetalk_message', to: 'firetalk_messages#new'
  post '/firetalk_message', to: 'firetalk_messages#create'

  resources :users do
    get :validate_email
    resources :debates
    resources :firetalks
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :debates
end

app/models/debate.rb
class Debate < ActiveRecord::Base
	require 'opentok'
	OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

	before_create :save_tok_session_id

	belongs_to :user
	belongs_to :category
	belongs_to :debate_style
	has_many :debate_users
	has_many :debater_invites
	has_many :moderator_invites

	accepts_nested_attributes_for :debater_invites
	accepts_nested_attributes_for :moderator_invites

	private
	def save_tok_session_id
		opentok = OpenTok::OpenTok.new '45241592', 'b099560439c52ed195d79cb7c15fbae1d9b33f1e'
		session = opentok.create_session
		self.tok_session_id = session.session_id
	end
end

app/models/debate_invites.rb
class DebateInvites < ActiveRecord::Base
  belongs_to :debate
end

app/models/debate_styles.rb
class DebateStyles < ActiveRecord::Base
  has_many :debates
end

app/models/debate_user.rb
class DebateUser < ActiveRecord::Base
	belongs_to :debate
	belongs_to :user
end

app/models/debater_invite.rb
class DebaterInvite < ActiveRecord::Base

  after_create :send_invite

  belongs_to :debate
  belongs_to :user
  
  private
  def send_invite
  end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/firetalk.rb
class Firetalk < ActiveRecord::Base
  require 'opentok'
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  before_create :save_tok_session_id

  #attr_accessible :user_ids
  belongs_to :user
  has_many :firetalk_debaters
  has_many :firetalk_messages
  has_many :users, :through => :firetalk_debaters

  accepts_nested_attributes_for :firetalk_debaters
  attr_reader :user_tokens
  #validates :user, presence: true

  def user_tokens=(ids)
    # TODO: validate users with ids, not working for now
    #self.user_ids = ids.split(",")
  end

  def random_firetalk(params)
    self.user_id = params[:user_id]
    self.topic = params[:topic]
    self.tok_session_id = params[:tok_session_id]
    self.name = "Random Firetalk!"
  end

  private
  def save_tok_session_id
    opentok = OpenTok::OpenTok.new '45241592', 'b099560439c52ed195d79cb7c15fbae1d9b33f1e'
    session = opentok.create_session
    self.tok_session_id = session.session_id
  end
end

app/models/firetalk_debater.rb
class FiretalkDebater < ActiveRecord::Base
  belongs_to :firetalk
  belongs_to :user
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user 
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :validate_code
	before_create :save_fullname
	has_many :debates
	has_many :firetalks
	has_many :debate_users
	has_many :firetalk_users
	has_many :posts

	has_many :invites
	has_many :moderator_invites
	has_many :notifications

	has_secure_password
	validates :password, presence: true, confirmation: true, length: { minimum: 7 }
	validates_uniqueness_of :email, :case_sensitive => false

	private
	def validate_code
		if self.validation_code.nil? || self.validation_code.blank
			self.validation_code = SecureRandom.urlsafe_base64.to_s
		end
	end

	def save_fullname
		self.fullname = self.firstname + " " + self.lastname
	end
end

app/helpers/debates_helper.rb
module DebatesHelper
  def link_to_add_moderator_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_moderator_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer-container">

	<div class="footer">

<div class="footer-feedback">

<em>
	Thanks for visiting our site! We need your feedback!
		<%= link_to("Tell us how we're doing.", '/feedbacks/new') %>
	</em>


</div>

<div class="fb-like" data-href="https://www.facebook.com/debatablelive/" data-layout="standard" data-action="like" data-show-faces="false" data-share="true">
</div>

</div>

</div>

app/views/layouts/_header.html.erb
<div class="section navbar-container">
  <div class="navwidth">
      <ul class="navcontainer">
        <li class="navlogo-container mobile-no">
          <%= link_to image_tag("debatable-logo.png", :class => "navlogo"), root_path, {:method => 'GET'} %>
        </li>
        <li class="navlogo-container desktop-no">
          <%= link_to image_tag("logo.png", :class => "navlogo"), root_path, {:method => 'GET'} %>
        </li>
        <ul class="navlog">
          <% if session[:user_id] != nil %>

          <li class="navbar-link">
            <%= link_to 'New Firetalk', new_user_firetalk_path(@user), {:method => 'GET'} %>
          </li>
          <li class="navbar-link">
            <%= link_to('My Profile', @user) %>
          </li>
          <li class="navbar-link">
            <%= link_to 'Logout', logout_path, {:method => 'GET'} %>
          </li>
          <!--
          <div id="invitesContainer" data-url="<%= '/invites' %>">
            <% @invites.each do |invite| %>
            <%= render invite, :locals => {:invite => invite} %>
          <% end %>
        -->

        <% else %>
        <li class="navbar-link">
          <%= link_to "Signup", new_user_path, {:method => 'GET'} %>
        </li>
        <li class="navbar-link">
        <%= link_to 'Login', login_path, {:method => 'GET'} %>
        <% end %>
</li>
</ul>
</ul>
</div>
</div>


<div class="beta-flag">
<%= image_tag("betaFlag.png")%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Debatable
  </title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'token-input' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'logo-fav.png' %>
  <link href='https://fonts.googleapis.com/css?family=Karla' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
  <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script-->
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=281009785261501";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    

    <div class="section group header-span">
      <%= render 'layouts/header' %>
    </div>
<div class="app-flex">
<div>
    <%= yield %>
  </div>

    <div class="footer-app">
    <%= render 'layouts/footer' %>
  </div>
</div>
</body>
</html>